################################################################################
# File Name: _production_schema_snapshot.py
# Purpose/Description: US-807 -- GENERATED. The deployed server schema, read
#   from production by scripts/snapshot_production_schema.py. Do not hand-edit:
#   re-run the script. The A-4 applied-schema parity gate builds its CI database
#   from this, stamps the ledger, then runs every newer migration forward.
################################################################################

"""Production server schema, pinned (GENERATED -- re-run the script, never edit)."""

from __future__ import annotations

DATABASE: str = 'obd2db'
SERVER_VERSION: str = '11.8.6-MariaDB-0+deb13u1 from Debian'
MEASURED_AT: str = '2026-10-06T21:55:08Z'

# The migrations production had applied when this was read, in order.
PRODUCTION_LEDGER: tuple[str, ...] = (
    '0001',
    '0002',
    '0003',
    '0004',
    '0005',
    '0006',
    '0007',
    '0008',
    '0009',
    '0010',
    '0011',
    '0012',
    '0013',
    '0014',
    '0015',
    '0016',
    '0017',
    '0018',
    '0019',
    '0020',
    '0021',
    '0022',
    '0023',
    '0024',
    '0025',
    '0026',
    '0027',
    '0028',
    '0029',
    '0030',
    '0031',
    '0032',
    '0033',
    '0034',
    '0035',
)

# SHOW CREATE TABLE for every base table except the ledger (the harness
# rebuilds that), with the AUTO_INCREMENT row counter removed.
PRODUCTION_TABLE_DDL: dict[str, str] = {
    'ai_recommendations': '''CREATE TABLE `ai_recommendations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `timestamp` datetime NOT NULL DEFAULT current_timestamp(),
  `recommendation` text NOT NULL,
  `priority_rank` int(11) DEFAULT NULL,
  `is_duplicate_of` int(11) DEFAULT NULL,
  `profile_id` varchar(64) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `source_device` (`source_device`,`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'alert_log': '''CREATE TABLE `alert_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `timestamp` datetime NOT NULL DEFAULT current_timestamp(),
  `alert_type` varchar(64) NOT NULL,
  `parameter_name` varchar(128) NOT NULL,
  `value` float NOT NULL,
  `threshold` float NOT NULL,
  `profile_id` varchar(64) DEFAULT NULL,
  `drive_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `source_device` (`source_device`,`source_id`),
  KEY `IX_alert_log_drive_id` (`drive_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'analysis_history': '''CREATE TABLE `analysis_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `drive_id` int(11) DEFAULT NULL,
  `model_name` varchar(64) NOT NULL,
  `started_at` datetime NOT NULL DEFAULT current_timestamp(),
  `completed_at` datetime DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `result_summary` text DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'anomaly_log': '''CREATE TABLE `anomaly_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `drive_id` int(11) NOT NULL,
  `parameter_name` varchar(128) NOT NULL,
  `observed_value` float NOT NULL,
  `expected_min` float DEFAULT NULL,
  `expected_max` float DEFAULT NULL,
  `deviation_sigma` float NOT NULL,
  `severity` varchar(16) NOT NULL,
  `detected_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'baselines': '''CREATE TABLE `baselines` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_id` varchar(64) NOT NULL,
  `parameter_name` varchar(128) NOT NULL,
  `avg_value` double NOT NULL,
  `min_value` double DEFAULT NULL,
  `max_value` double DEFAULT NULL,
  `std_dev` double DEFAULT NULL,
  `sample_count` int(11) DEFAULT NULL,
  `established_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_baselines_device_param` (`device_id`,`parameter_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'battery_health_log': '''CREATE TABLE `battery_health_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `start_timestamp` datetime NOT NULL DEFAULT current_timestamp(),
  `end_timestamp` datetime DEFAULT NULL,
  `runtime_seconds` int(11) DEFAULT NULL,
  `ambient_temp_c` float DEFAULT NULL,
  `load_class` varchar(16) NOT NULL DEFAULT 'production',
  `notes` text DEFAULT NULL,
  `data_source` varchar(16) DEFAULT 'real',
  `close_reason` varchar(32) DEFAULT NULL,
  `start_vcell_v` float DEFAULT NULL,
  `end_vcell_v` float DEFAULT NULL,
  `start_soc_pct` float DEFAULT NULL,
  `end_soc_pct` float DEFAULT NULL,
  `drain_trigger` varchar(16) NOT NULL DEFAULT 'keyoff',
  `cell_epoch` varchar(32) DEFAULT NULL,
  `cut_step_mv` float DEFAULT NULL,
  `window_start_s` int(11) DEFAULT NULL,
  `window_end_s` int(11) DEFAULT NULL,
  `drain_rate_mv_s` float DEFAULT NULL,
  `verdict` varchar(16) DEFAULT NULL,
  `t_floor_s` int(11) DEFAULT NULL,
  `floor_vcell_v` float DEFAULT NULL,
  `cutoff_vcell_v` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_battery_health_log_source` (`source_device`,`source_id`),
  CONSTRAINT `ck_battery_health_log_close_reason` CHECK (`close_reason` in ('clean','reaped_uncheckpointed','reaped_checkpointed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'calibration_sessions': '''CREATE TABLE `calibration_sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `start_time` datetime NOT NULL DEFAULT current_timestamp(),
  `end_time` datetime DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `profile_id` varchar(64) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `data_source` varchar(16) NOT NULL DEFAULT 'real',
  PRIMARY KEY (`id`),
  UNIQUE KEY `source_device` (`source_device`,`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'connection_log': '''CREATE TABLE `connection_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `timestamp` datetime NOT NULL DEFAULT current_timestamp(),
  `event_type` varchar(64) NOT NULL,
  `mac_address` varchar(17) DEFAULT NULL,
  `success` int(11) NOT NULL,
  `error_message` text DEFAULT NULL,
  `retry_count` int(11) DEFAULT NULL,
  `data_source` varchar(16) NOT NULL DEFAULT 'real',
  `drive_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `source_device` (`source_device`,`source_id`),
  KEY `IX_connection_log_drive_id` (`drive_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'devices': '''CREATE TABLE `devices` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_id` varchar(64) NOT NULL,
  `display_name` varchar(128) DEFAULT NULL,
  `last_seen` datetime DEFAULT NULL,
  `api_key_hash` varchar(128) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `device_id` (`device_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'drain_vcell_trajectory': '''CREATE TABLE `drain_vcell_trajectory` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `ts_utc` datetime NOT NULL,
  `ts_capture` double NOT NULL,
  `seq` int(11) NOT NULL,
  `vcell_v` float DEFAULT NULL,
  `termination_reason` varchar(32) DEFAULT NULL,
  `cell_epoch` varchar(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_drain_vcell_trajectory_source` (`source_device`,`source_id`),
  CONSTRAINT `ck_drain_vcell_trajectory_termination_reason` CHECK (`termination_reason` in ('shutdown','power_restored','drain_floor','vcell_floor','vcell_unreadable'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'drive_annotations': "CREATE TABLE `drive_annotations` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `drive_id` int(11) NOT NULL,\n  `source_device` varchar(64) NOT NULL DEFAULT 'chi-eclipse-01',\n  `captured_at` datetime NOT NULL DEFAULT current_timestamp(),\n  `captured_by` varchar(32) NOT NULL DEFAULT 'spool',\n  `fuel_grade` smallint(6) DEFAULT NULL,\n  `fuel_level_at_start` varchar(16) DEFAULT NULL,\n  `last_fill_date` date DEFAULT NULL,\n  `ambient_temp_f` decimal(5,1) DEFAULT NULL,\n  `weather` varchar(64) DEFAULT NULL,\n  `engine_soak_state` varchar(32) DEFAULT NULL,\n  `route` varchar(255) DEFAULT NULL,\n  `driving_intent` varchar(64) DEFAULT NULL,\n  `anything_unusual` text DEFAULT NULL,\n  `spool_notes` text DEFAULT NULL,\n  `is_actual_drive` tinyint(1) DEFAULT 1,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_drive` (`source_device`,`drive_id`),\n  KEY `idx_drive_id` (`drive_id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='Spool-owned drive annotations sidecar (2026-05-09).'",
    'drive_counter': '''CREATE TABLE `drive_counter` (
  `id` int(11) NOT NULL CHECK (`id` = 1),
  `last_drive_id` bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'drive_derived_signals': '''CREATE TABLE `drive_derived_signals` (
  `summary_id` int(11) NOT NULL,
  `estimated_distance_km` float DEFAULT NULL,
  `peak_acceleration_ms2` float DEFAULT NULL,
  `peak_deceleration_ms2` float DEFAULT NULL,
  `sample_count` int(11) NOT NULL,
  `segment_count` int(11) NOT NULL,
  `gap_skipped_count` int(11) NOT NULL,
  `speed_unit` varchar(16) NOT NULL DEFAULT 'km/h',
  `distance_unit` varchar(16) NOT NULL DEFAULT 'km',
  `accel_unit` varchar(16) NOT NULL DEFAULT 'm/s^2',
  `computed_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`summary_id`),
  CONSTRAINT `fk_drive_derived_signals_drives` FOREIGN KEY (`summary_id`) REFERENCES `drives` (`drive_id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'drive_statistics': '''CREATE TABLE `drive_statistics` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `summary_id` int(11) NOT NULL,
  `parameter_name` varchar(128) NOT NULL,
  `min_value` float DEFAULT NULL,
  `max_value` float DEFAULT NULL,
  `avg_value` float DEFAULT NULL,
  `std_dev` float DEFAULT NULL,
  `outlier_min` float DEFAULT NULL,
  `outlier_max` float DEFAULT NULL,
  `sample_count` int(11) DEFAULT NULL,
  `computed_at` datetime DEFAULT current_timestamp(),
  `data_quality` varchar(20) NOT NULL DEFAULT 'unassessed',
  PRIMARY KEY (`id`),
  KEY `idx_drive_statistics_quality` (`data_quality`),
  KEY `fk_drive_statistics_drives` (`summary_id`),
  CONSTRAINT `fk_drive_statistics_drives` FOREIGN KEY (`summary_id`) REFERENCES `drives` (`drive_id`) ON DELETE CASCADE,
  CONSTRAINT `ck_drive_statistics_data_quality` CHECK (`data_quality` in ('unassessed','full','sparse','below_threshold','attribution_anomaly','foreign_vehicle'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'drive_summary': '''CREATE TABLE `drive_summary` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_id` varchar(64) DEFAULT NULL,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `duration_seconds` int(11) DEFAULT NULL,
  `profile_id` varchar(64) DEFAULT NULL,
  `row_count` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `source_id` int(11) DEFAULT NULL,
  `source_device` varchar(64) DEFAULT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `drive_id` int(11) DEFAULT NULL,
  `drive_start_timestamp` datetime DEFAULT NULL,
  `intake_air_temp_at_start_c` float DEFAULT NULL,
  `starting_battery_v` float DEFAULT NULL,
  `barometric_kpa_at_start` float DEFAULT NULL,
  `is_real` tinyint(1) DEFAULT NULL,
  `data_source` varchar(16) DEFAULT 'real',
  `data_quality` varchar(20) NOT NULL DEFAULT 'unassessed',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_drive_summary_source` (`source_device`,`source_id`),
  KEY `IX_drive_summary_drive_id` (`drive_id`),
  KEY `idx_drive_summary_data_quality` (`data_quality`),
  CONSTRAINT `chk_drive_id_source_id` CHECK (`drive_id` is null and `source_id` is null or `drive_id` is not null and `source_id` is not null and `drive_id` = `source_id`),
  CONSTRAINT `ck_drive_summary_data_quality` CHECK (`data_quality` in ('unassessed','full','attribution_anomaly','foreign_vehicle'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'drives': '''CREATE TABLE `drives` (
  `drive_id` int(11) NOT NULL AUTO_INCREMENT,
  `source_device` varchar(64) DEFAULT NULL,
  `source_drive_id` int(11) DEFAULT NULL,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `data_source` varchar(16) DEFAULT 'real',
  `data_quality` varchar(20) NOT NULL DEFAULT 'unassessed',
  PRIMARY KEY (`drive_id`),
  UNIQUE KEY `uq_drives_source_device_source_drive_id` (`source_device`,`source_drive_id`),
  CONSTRAINT `ck_drives_data_quality` CHECK (`data_quality` in ('unassessed','full','attribution_anomaly','foreign_vehicle','unmappable_legacy'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'dtc_freeze_frame': '''CREATE TABLE `dtc_freeze_frame` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `dtc_log_id` int(11) DEFAULT NULL,
  `captured_at_timestamp_utc` datetime NOT NULL,
  `pid_responses_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`pid_responses_json`)),
  `vehicle_info_id` int(11) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_dtc_freeze_frame_source` (`source_device`,`source_id`),
  KEY `ix_dtc_freeze_frame_dtc_log_id` (`dtc_log_id`),
  KEY `ix_dtc_freeze_frame_vehicle_info_id` (`vehicle_info_id`),
  CONSTRAINT `fk_dtc_freeze_frame_dtc_log` FOREIGN KEY (`dtc_log_id`) REFERENCES `dtc_log` (`id`),
  CONSTRAINT `fk_dtc_freeze_frame_vehicle_info` FOREIGN KEY (`vehicle_info_id`) REFERENCES `vehicle_info` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'dtc_log': '''CREATE TABLE `dtc_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `dtc_code` varchar(16) NOT NULL,
  `description` text DEFAULT NULL,
  `status` varchar(16) NOT NULL,
  `first_seen_timestamp` datetime NOT NULL DEFAULT current_timestamp(),
  `last_seen_timestamp` datetime NOT NULL DEFAULT current_timestamp(),
  `drive_id` int(11) DEFAULT NULL,
  `data_source` varchar(16) DEFAULT 'real',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_dtc_log_source` (`source_device`,`source_id`),
  KEY `ix_dtc_log_drive_id` (`drive_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'ecu': "CREATE TABLE `ecu` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `ecu_signature` varchar(32) NOT NULL,\n  `cal_signature` varchar(32) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uq_ecu_signature_cal_signature` (`ecu_signature`,`cal_signature`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ECU identity is immutable: an (ecu_signature, cal_signature) pair is a stable identity and a reflash is a NEW row, never an in-place edit.  SOLE sanctioned in-place mutation: resolving a write-once UNKCAL cal_signature to the real CALID once known (Spool Q5) -- this is distinct from a reflash (which is a new row).  vehicle_info.ecu_id references a SPECIFIC identity row; per-lineage-row identity is otherwise immutable.'",
    'edr_imu_derived': '''CREATE TABLE `edr_imu_derived` (
  `source_device` varchar(64) NOT NULL,
  `source_id` bigint(20) NOT NULL,
  `ts_utc` datetime NOT NULL,
  `ts_capture` double NOT NULL,
  `seq` int(11) NOT NULL,
  `pitch_deg` float DEFAULT NULL,
  `stop_count` int(11) DEFAULT NULL,
  `bias_rad` float DEFAULT NULL,
  `fusion_version` int(11) NOT NULL,
  `drive_id` int(11) DEFAULT NULL,
  `data_source` varchar(16) NOT NULL,
  `schema_version` int(11) NOT NULL,
  `gyro_bias_roll_rad_s` float DEFAULT NULL,
  `gyro_bias_pitch_rad_s` float DEFAULT NULL,
  `gyro_bias_yaw_rad_s` float DEFAULT NULL,
  `gyro_bias_stops` int(11) DEFAULT NULL,
  `gyro_bias_rejected_stops` int(11) DEFAULT NULL,
  `synced_at` datetime DEFAULT NULL,
  `sync_batch_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`source_device`,`source_id`,`ts_utc`),
  KEY `ix_edr_imu_derived_device_ts` (`source_device`,`ts_utc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci `PAGE_COMPRESSED`=1
 PARTITION BY RANGE  COLUMNS(`ts_utc`)
(PARTITION `p202609` VALUES LESS THAN ('2026-10-01') ENGINE = InnoDB,
 PARTITION `p202610` VALUES LESS THAN ('2026-11-01') ENGINE = InnoDB,
 PARTITION `p202611` VALUES LESS THAN ('2026-12-01') ENGINE = InnoDB,
 PARTITION `p202612` VALUES LESS THAN ('2027-01-01') ENGINE = InnoDB,
 PARTITION `p202701` VALUES LESS THAN ('2027-02-01') ENGINE = InnoDB,
 PARTITION `p202702` VALUES LESS THAN ('2027-03-01') ENGINE = InnoDB,
 PARTITION `p202703` VALUES LESS THAN ('2027-04-01') ENGINE = InnoDB,
 PARTITION `p202704` VALUES LESS THAN ('2027-05-01') ENGINE = InnoDB,
 PARTITION `p202705` VALUES LESS THAN ('2027-06-01') ENGINE = InnoDB,
 PARTITION `p202706` VALUES LESS THAN ('2027-07-01') ENGINE = InnoDB,
 PARTITION `p202707` VALUES LESS THAN ('2027-08-01') ENGINE = InnoDB,
 PARTITION `p202708` VALUES LESS THAN ('2027-09-01') ENGINE = InnoDB,
 PARTITION `pmax` VALUES LESS THAN (MAXVALUE) ENGINE = InnoDB)''',
    'edr_imu_sample': '''CREATE TABLE `edr_imu_sample` (
  `source_device` varchar(64) NOT NULL,
  `source_id` bigint(20) NOT NULL,
  `ts_utc` datetime NOT NULL,
  `ts_capture` double NOT NULL,
  `seq` int(11) NOT NULL,
  `accel_x` float DEFAULT NULL,
  `accel_y` float DEFAULT NULL,
  `accel_z` float DEFAULT NULL,
  `gyro_x` float DEFAULT NULL,
  `gyro_y` float DEFAULT NULL,
  `gyro_z` float DEFAULT NULL,
  `mag_x` float DEFAULT NULL,
  `mag_y` float DEFAULT NULL,
  `mag_z` float DEFAULT NULL,
  `temp_c` float DEFAULT NULL,
  `drive_id` int(11) DEFAULT NULL,
  `data_source` varchar(16) NOT NULL,
  `schema_version` int(11) NOT NULL,
  `synced_at` datetime DEFAULT NULL,
  `sync_batch_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`source_device`,`source_id`,`ts_utc`),
  KEY `ix_edr_imu_sample_device_ts` (`source_device`,`ts_utc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci `PAGE_COMPRESSED`=1
 PARTITION BY RANGE  COLUMNS(`ts_utc`)
(PARTITION `p202609` VALUES LESS THAN ('2026-10-01') ENGINE = InnoDB,
 PARTITION `p202610` VALUES LESS THAN ('2026-11-01') ENGINE = InnoDB,
 PARTITION `p202611` VALUES LESS THAN ('2026-12-01') ENGINE = InnoDB,
 PARTITION `p202612` VALUES LESS THAN ('2027-01-01') ENGINE = InnoDB,
 PARTITION `p202701` VALUES LESS THAN ('2027-02-01') ENGINE = InnoDB,
 PARTITION `p202702` VALUES LESS THAN ('2027-03-01') ENGINE = InnoDB,
 PARTITION `p202703` VALUES LESS THAN ('2027-04-01') ENGINE = InnoDB,
 PARTITION `p202704` VALUES LESS THAN ('2027-05-01') ENGINE = InnoDB,
 PARTITION `p202705` VALUES LESS THAN ('2027-06-01') ENGINE = InnoDB,
 PARTITION `p202706` VALUES LESS THAN ('2027-07-01') ENGINE = InnoDB,
 PARTITION `p202707` VALUES LESS THAN ('2027-08-01') ENGINE = InnoDB,
 PARTITION `p202708` VALUES LESS THAN ('2027-09-01') ENGINE = InnoDB,
 PARTITION `pmax` VALUES LESS THAN (MAXVALUE) ENGINE = InnoDB)''',
    'edr_light_sample': '''CREATE TABLE `edr_light_sample` (
  `source_device` varchar(64) NOT NULL,
  `source_id` bigint(20) NOT NULL,
  `ts_utc` datetime NOT NULL,
  `ts_capture` double NOT NULL,
  `seq` int(11) NOT NULL,
  `lux` float DEFAULT NULL,
  `visible` int(11) DEFAULT NULL,
  `infrared` int(11) DEFAULT NULL,
  `full_spectrum` int(11) DEFAULT NULL,
  `gain` varchar(16) DEFAULT NULL,
  `integration_ms` int(11) DEFAULT NULL,
  `drive_id` int(11) DEFAULT NULL,
  `data_source` varchar(16) NOT NULL,
  `schema_version` int(11) NOT NULL,
  `synced_at` datetime DEFAULT NULL,
  `sync_batch_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`source_device`,`source_id`,`ts_utc`),
  KEY `ix_edr_light_sample_device_ts` (`source_device`,`ts_utc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci `PAGE_COMPRESSED`=1
 PARTITION BY RANGE  COLUMNS(`ts_utc`)
(PARTITION `p202609` VALUES LESS THAN ('2026-10-01') ENGINE = InnoDB,
 PARTITION `p202610` VALUES LESS THAN ('2026-11-01') ENGINE = InnoDB,
 PARTITION `p202611` VALUES LESS THAN ('2026-12-01') ENGINE = InnoDB,
 PARTITION `p202612` VALUES LESS THAN ('2027-01-01') ENGINE = InnoDB,
 PARTITION `p202701` VALUES LESS THAN ('2027-02-01') ENGINE = InnoDB,
 PARTITION `p202702` VALUES LESS THAN ('2027-03-01') ENGINE = InnoDB,
 PARTITION `p202703` VALUES LESS THAN ('2027-04-01') ENGINE = InnoDB,
 PARTITION `p202704` VALUES LESS THAN ('2027-05-01') ENGINE = InnoDB,
 PARTITION `p202705` VALUES LESS THAN ('2027-06-01') ENGINE = InnoDB,
 PARTITION `p202706` VALUES LESS THAN ('2027-07-01') ENGINE = InnoDB,
 PARTITION `p202707` VALUES LESS THAN ('2027-08-01') ENGINE = InnoDB,
 PARTITION `p202708` VALUES LESS THAN ('2027-09-01') ENGINE = InnoDB,
 PARTITION `pmax` VALUES LESS THAN (MAXVALUE) ENGINE = InnoDB)''',
    'maintenance_log': "CREATE TABLE `maintenance_log` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `event_date` date NOT NULL,\n  `event_date_precision` varchar(8) NOT NULL,\n  `event_date_certainty` varchar(16) NOT NULL,\n  `event_date_end` date DEFAULT NULL,\n  `odometer_mi` int(11) DEFAULT NULL,\n  `odometer_source` varchar(32) DEFAULT NULL,\n  `work_performed` text NOT NULL,\n  `source_verbatim` text DEFAULT NULL,\n  `dtc_code` varchar(16) DEFAULT NULL,\n  `venue` varchar(128) DEFAULT NULL,\n  `document_ref` varchar(64) DEFAULT NULL,\n  `source_document_path` text DEFAULT NULL,\n  `parts` text DEFAULT NULL,\n  `part_customer_supplied` tinyint(1) DEFAULT NULL,\n  `cost_usd` float DEFAULT NULL,\n  `is_epoch_boundary` tinyint(1) NOT NULL DEFAULT 0,\n  `provenance` text NOT NULL,\n  `notes` text DEFAULT NULL,\n  `recorded_by` varchar(64) NOT NULL,\n  `recorded_at` datetime DEFAULT current_timestamp(),\n  PRIMARY KEY (`id`),\n  KEY `ix_maintenance_log_event_date` (`event_date`),\n  CONSTRAINT `ck_maintenance_log_odometer_paired` CHECK (`odometer_mi` is null and `odometer_source` is null or `odometer_mi` is not null and `odometer_source` is not null),\n  CONSTRAINT `ck_maintenance_log_date_precision` CHECK (`event_date_precision` in ('day','month','year','range')),\n  CONSTRAINT `ck_maintenance_log_odometer_source` CHECK (`odometer_source` is null or `odometer_source` in ('shop_record','photo_exif','owner_reported','state_agency_rounded','project_telemetry')),\n  CONSTRAINT `ck_maintenance_log_date_certainty` CHECK (`event_date_certainty` in ('exact','estimated')),\n  CONSTRAINT `ck_maintenance_log_date_certainty_vs_precision` CHECK (`event_date_precision` = 'day' or `event_date_certainty` = 'estimated'),\n  CONSTRAINT `ck_maintenance_log_range_end` CHECK (`event_date_precision` = 'range' and `event_date_end` is not null or `event_date_precision` <> 'range' and `event_date_end` is null)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ARCH-020: what was DONE to the vehicle. Provenance is PER FIELD in the provenance column, never per row.'",
    'maintenance_schedule': "CREATE TABLE `maintenance_schedule` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `item` varchar(128) NOT NULL,\n  `interval_miles` int(11) DEFAULT NULL,\n  `interval_months` int(11) DEFAULT NULL,\n  `interval_engine_hours` int(11) DEFAULT NULL,\n  `last_done_log_id` int(11) DEFAULT NULL,\n  `last_done_confidence` varchar(16) NOT NULL,\n  `notes` text DEFAULT NULL,\n  `recorded_by` varchar(64) NOT NULL,\n  `recorded_at` datetime DEFAULT current_timestamp(),\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `uq_maintenance_schedule_item` (`item`),\n  KEY `fk_schedule_last_done_log` (`last_done_log_id`),\n  CONSTRAINT `fk_schedule_last_done_log` FOREIGN KEY (`last_done_log_id`) REFERENCES `maintenance_log` (`id`),\n  CONSTRAINT `ck_maintenance_schedule_some_interval` CHECK (`interval_miles` is not null or `interval_months` is not null or `interval_engine_hours` is not null),\n  CONSTRAINT `ck_maintenance_schedule_confidence` CHECK (`last_done_confidence` in ('confirmed','inferred','unknown'))\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ARCH-020: what is DUE. Three interval columns because at ~500 mi/yr only calendar intervals can ever fire.'",
    'pi_state': '''CREATE TABLE `pi_state` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `no_new_drives` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_pi_state_source` (`source_device`,`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'power_log': '''CREATE TABLE `power_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `timestamp` datetime NOT NULL DEFAULT current_timestamp(),
  `event_type` varchar(32) NOT NULL,
  `power_source` varchar(32) NOT NULL,
  `on_ac_power` int(11) NOT NULL DEFAULT 1,
  `vcell` float DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_power_log_source` (`source_device`,`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'profiles': '''CREATE TABLE `profiles` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `source_profile_id` varchar(64) DEFAULT NULL,
  `name` varchar(128) NOT NULL,
  `description` text DEFAULT NULL,
  `polling_interval_ms` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp(),
  `data_source` varchar(16) NOT NULL DEFAULT 'real',
  PRIMARY KEY (`id`),
  UNIQUE KEY `source_device` (`source_device`,`source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'realtime_data': '''CREATE TABLE `realtime_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `timestamp` datetime NOT NULL,
  `parameter_name` varchar(128) NOT NULL,
  `value` float NOT NULL,
  `unit` varchar(32) DEFAULT NULL,
  `profile_id` varchar(64) DEFAULT NULL,
  `data_source` varchar(16) NOT NULL DEFAULT 'real',
  `drive_id` bigint(20) DEFAULT NULL,
  `written_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `source_device` (`source_device`,`source_id`),
  KEY `IX_realtime_data_drive_id` (`drive_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'speed_pid_calibration': '''CREATE TABLE `speed_pid_calibration` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `correction_factor` double NOT NULL,
  `capture_method` varchar(32) DEFAULT NULL,
  `captured_at_timestamp_utc` datetime DEFAULT NULL,
  `captured_by` varchar(128) DEFAULT NULL,
  `provenance` text NOT NULL,
  `notes` text DEFAULT NULL,
  `ecu_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_speed_pid_calibration_ecu_id` (`ecu_id`),
  CONSTRAINT `fk_speed_pid_calibration_ecu` FOREIGN KEY (`ecu_id`) REFERENCES `ecu` (`id`),
  CONSTRAINT `ck_speed_pid_calibration_capture_method` CHECK (`capture_method` in ('gps_correlation','gear_math','vendor_spec','default'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'startup_log': '''CREATE TABLE `startup_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `boot_id` varchar(64) NOT NULL,
  `prior_boot_clean` int(11) DEFAULT NULL,
  `prior_last_entry_ts` varchar(40) DEFAULT NULL,
  `current_boot_first_entry_ts` varchar(40) DEFAULT NULL,
  `prior_boot_last_stage` varchar(64) DEFAULT NULL,
  `prior_boot_reason` varchar(64) DEFAULT NULL,
  `recorded_at` varchar(40) DEFAULT NULL,
  `prior_boot_home_state` varchar(64) DEFAULT NULL,
  `prior_boot_sync_outcome` varchar(64) DEFAULT NULL,
  `prior_boot_backlog_start` int(11) DEFAULT NULL,
  `prior_boot_backlog_end` int(11) DEFAULT NULL,
  `prior_boot_sync_started_at` varchar(40) DEFAULT NULL,
  `prior_boot_sync_ended_at` varchar(40) DEFAULT NULL,
  `prior_boot_vcell_before_cut_v` float DEFAULT NULL,
  `prior_boot_loss_at` varchar(40) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_startup_log_boot` (`source_device`,`boot_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'statistics': '''CREATE TABLE `statistics` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `source_id` int(11) NOT NULL,
  `source_device` varchar(64) NOT NULL,
  `synced_at` datetime DEFAULT current_timestamp(),
  `sync_batch_id` int(11) DEFAULT NULL,
  `parameter_name` varchar(128) NOT NULL,
  `analysis_date` datetime NOT NULL,
  `profile_id` varchar(64) NOT NULL,
  `max_value` float DEFAULT NULL,
  `min_value` float DEFAULT NULL,
  `avg_value` float DEFAULT NULL,
  `mode_value` float DEFAULT NULL,
  `std_1` float DEFAULT NULL,
  `std_2` float DEFAULT NULL,
  `outlier_min` float DEFAULT NULL,
  `outlier_max` float DEFAULT NULL,
  `sample_count` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `data_source` varchar(16) NOT NULL DEFAULT 'real',
  `drive_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `source_device` (`source_device`,`source_id`),
  KEY `IX_statistics_drive_id` (`drive_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'sync_history': '''CREATE TABLE `sync_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `device_id` varchar(64) NOT NULL,
  `started_at` datetime NOT NULL DEFAULT current_timestamp(),
  `completed_at` datetime DEFAULT NULL,
  `rows_synced` int(11) DEFAULT NULL,
  `status` varchar(32) NOT NULL,
  `tables_synced` text DEFAULT NULL,
  `error_message` text DEFAULT NULL,
  `residual_rows` int(11) DEFAULT NULL,
  `residual_complete` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'trend_snapshots': '''CREATE TABLE `trend_snapshots` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parameter_name` varchar(128) NOT NULL,
  `window_size` int(11) NOT NULL,
  `direction` varchar(16) NOT NULL,
  `slope` float DEFAULT NULL,
  `avg_peak` float DEFAULT NULL,
  `avg_mean` float DEFAULT NULL,
  `drift_pct` float DEFAULT NULL,
  `computed_at` datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci''',
    'vehicle_info': "CREATE TABLE `vehicle_info` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `source_id` int(11) NOT NULL,\n  `source_device` varchar(64) NOT NULL,\n  `synced_at` datetime DEFAULT current_timestamp(),\n  `vin` varchar(17) DEFAULT NULL,\n  `make` varchar(64) DEFAULT NULL,\n  `model` varchar(64) DEFAULT NULL,\n  `year` int(11) DEFAULT NULL,\n  `engine` varchar(128) DEFAULT NULL,\n  `fuel_type` varchar(32) DEFAULT NULL,\n  `transmission` varchar(64) DEFAULT NULL,\n  `drive_type` varchar(32) DEFAULT NULL,\n  `body_class` varchar(64) DEFAULT NULL,\n  `plant_city` varchar(64) DEFAULT NULL,\n  `plant_country` varchar(64) DEFAULT NULL,\n  `raw_api_response` text DEFAULT NULL,\n  `created_at` datetime DEFAULT current_timestamp(),\n  `updated_at` datetime DEFAULT current_timestamp(),\n  `ecu_signature` text NOT NULL,\n  `cal_signature` text DEFAULT NULL,\n  `ecu_install_timestamp_utc` datetime NOT NULL,\n  `ecu_removal_timestamp_utc` datetime DEFAULT NULL,\n  `notes` text DEFAULT NULL,\n  `ecu_active_marker` int(11) GENERATED ALWAYS AS (case when `ecu_removal_timestamp_utc` is null then 1 else NULL end) STORED,\n  `ecu_id` int(11) NOT NULL,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `source_device` (`source_device`,`source_id`),\n  UNIQUE KEY `uq_vehicle_info_single_active` (`ecu_active_marker`),\n  KEY `fk_vehicle_info_ecu` (`ecu_id`),\n  CONSTRAINT `fk_vehicle_info_ecu` FOREIGN KEY (`ecu_id`) REFERENCES `ecu` (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='ECU-lineage identity columns are append-only: correct an ECU/cal signature by CLOSING the prior row (set ecu_removal_timestamp_utc) and OPENING a new row, never by UPDATEing identity columns in place.  dtc_freeze_frame (US-368) and per-drive joins reference a SPECIFIC row by FK + time window, so a mutated identity would silently rewrite history.  Sanctioned mutator: stamp_ecu_swap (US-366) close+open.  ecu_id (US-376 / B-076) is an immutable per-lineage-row identity reference into the normalized ecu dimension; the transitional ecu_signature/cal_signature TEXT columns are a derived snapshot kept coherent with that row (deprecated-transitional, drop in a later B-076 slice).'",
}
