################################################################################
# File Name: test_edr_raw_tables.py
# Purpose/Description: US-765 -- the server's EDR raw tables: ORM models with no
#                      surrogate id, their _TABLE_REGISTRY entries, the per-model
#                      upsert conflict columns (with every pre-existing table's
#                      upsert SQL pinned byte-identical), and migration v0026
#                      (idempotent, post-condition probed, DDL generated by
#                      src/common/edr/server_ddl.py rather than restated).
# Author: Rex (US-765)
# Creation Date: 2026-09-16
# Copyright: (c) 2026 Eclipse OBD-II Project. All rights reserved.
#
# Modification History:
# ================================================================================
# Date          | Author       | Description
# ================================================================================
# 2026-09-16    | Rex (US-765) | Initial.
# ================================================================================
################################################################################

"""US-765: the server has somewhere to put EDR samples.

The shape of both tables lives in ``src/common/edr`` (US-764). Nothing below
restates a column: the model is compared against the generator's output, and the
migration's SQL is compared against the generator's call.
"""

from __future__ import annotations

import re
from types import SimpleNamespace
from typing import Any

import pytest
from sqlalchemy import create_engine, func, select
from sqlalchemy.dialects import mysql, sqlite
from sqlalchemy.dialects.mysql import insert as mysql_insert
from sqlalchemy.dialects.sqlite import insert as sqlite_insert
from sqlalchemy.orm import Session
from sqlalchemy.schema import CreateTable

from scripts.apply_server_migrations import MigrationError
from src.common.edr.server_ddl import (
    DEVICE_TS_KEY_COLUMNS,
    PRIMARY_KEY_COLUMNS,
    buildRawTableDdl,
)
from src.common.edr.sync_contract import EDR_SYNC_TABLES
from src.server.api import sync as server_sync
from src.server.db.models import Base, EdrImuSample, EdrLightSample
from src.server.migrations import ALL_MIGRATIONS
from src.server.migrations.versions import v0026_us765_edr_raw_tables as mig

_DEVICE = "chi-eclipse-01"
_MODELS: dict[str, type] = {
    "edr_imu_sample": EdrImuSample,
    "edr_light_sample": EdrLightSample,
}

# MariaDB spells INTEGER and INT as one type; SQLAlchemy's MySQL compiler emits
# the long form while the generator emits the short one. This is the ONLY
# normalisation applied before comparing -- every other token must match.
_TYPE_SYNONYMS: dict[str, str] = {"INTEGER": "INT"}


# ---- helpers ------------------------------------------------------------------


def _generatorBody(tableName: str) -> list[str]:
    """The lines between ``CREATE TABLE (`` and ``) ENGINE`` of the generated DDL."""
    ddl = buildRawTableDdl(
        tableName, firstMonth=mig.FIRST_PARTITION_MONTH, months=mig.INITIAL_MONTHS,
    )
    body = ddl.split("(\n", 1)[1].split("\n) ENGINE", 1)[0]
    return [line.strip().rstrip(",") for line in body.splitlines()]


def _normaliseColumnLine(line: str) -> str:
    name, rest = line.split(" ", 1)
    typeName, _, tail = rest.partition(" ")
    typeName = _TYPE_SYNONYMS.get(typeName, typeName)
    return f"{name} {typeName}{(' ' + tail) if tail else ''}"


def _modelBody(model: type) -> list[str]:
    """The model's MariaDB column + primary key lines, as SQLAlchemy compiles them."""
    table = model.__table__  # type: ignore[attr-defined]
    ddl = str(CreateTable(table).compile(dialect=mysql.dialect()))
    body = ddl.split("(\n", 1)[1].rsplit("\n)", 1)[0]
    return [line.strip().rstrip(",") for line in body.splitlines() if line.strip()]


def _imuRow(piId: int, ts: str = "2026-09-14T16:32:57Z") -> dict[str, Any]:
    return {
        "id": piId, "ts_utc": ts, "ts_capture": 1693.5, "seq": piId,
        "accel_x": 0.1, "accel_y": -0.05, "accel_z": 9.8,
        "gyro_x": 0.0, "gyro_y": 0.0, "gyro_z": 0.0,
        "mag_x": 1.0, "mag_y": 2.0, "mag_z": 3.0, "temp_c": 30.0,
        "drive_id": None, "data_source": "real", "schema_version": 1,
    }


def _lightRow(piId: int, ts: str = "2026-09-14T16:32:57Z") -> dict[str, Any]:
    return {
        "id": piId, "ts_utc": ts, "ts_capture": 1693.5, "seq": piId,
        "lux": None, "visible": 120, "infrared": 40, "full_spectrum": 160,
        "gain": "med", "integration_ms": 100, "drive_id": 7,
        "data_source": "real", "schema_version": 1,
    }


@pytest.fixture()
def session():
    engine = create_engine("sqlite:///:memory:", future=True)
    Base.metadata.create_all(engine)
    with Session(engine) as s:
        yield s


# ---- the models ---------------------------------------------------------------


@pytest.mark.parametrize("tableName", EDR_SYNC_TABLES)
def test_model_hasNoIdColumn_andDeclaresTheGeneratorsKeyAsItsConflictColumns(
    tableName: str,
) -> None:
    """
    Given: the EDR server model for a contract table
    When: its columns and sync conflict key are inspected
    Then: there is no surrogate id, and the conflict key IS the generator's PK
    """
    model = _MODELS[tableName]
    names = {c.name for c in model.__table__.columns}  # type: ignore[attr-defined]

    assert "id" not in names
    assert model.__sync_conflict_cols__ == PRIMARY_KEY_COLUMNS  # type: ignore[attr-defined]
    pk = [c.name for c in model.__table__.primary_key.columns]  # type: ignore[attr-defined]
    assert tuple(pk) == PRIMARY_KEY_COLUMNS


@pytest.mark.parametrize("tableName", EDR_SYNC_TABLES)
def test_model_isRegisteredForSync(tableName: str) -> None:
    model, renames = server_sync._TABLE_REGISTRY[tableName]
    assert model is _MODELS[tableName]
    assert renames == ()
    assert tableName in server_sync.acceptedTables()


@pytest.mark.parametrize("tableName", EDR_SYNC_TABLES)
def test_model_compilesToTheGeneratorsColumnsAndPrimaryKey(tableName: str) -> None:
    """
    Given: server_ddl.py's generated DDL (the contract's one home)
    When: the ORM model is compiled for MariaDB
    Then: every column line and the PRIMARY KEY line agree, in order
    """
    generated = [
        line for line in _generatorBody(tableName) if not line.startswith("KEY ")
    ]
    compiled = _modelBody(_MODELS[tableName])

    assert [
        line if line.startswith("PRIMARY KEY") else _normaliseColumnLine(line)
        for line in compiled
    ] == generated


@pytest.mark.parametrize("tableName", EDR_SYNC_TABLES)
def test_model_carriesTheGeneratorsDeviceTsIndex(tableName: str) -> None:
    keyLine = next(line for line in _generatorBody(tableName) if line.startswith("KEY "))
    match = re.fullmatch(r"KEY (\w+) \((.+)\)", keyLine)
    assert match is not None
    indexes = {
        ix.name: tuple(c.name for c in ix.columns)
        for ix in _MODELS[tableName].__table__.indexes  # type: ignore[attr-defined]
    }
    assert indexes == {match.group(1): DEVICE_TS_KEY_COLUMNS}
    assert tuple(match.group(2).split(", ")) == DEVICE_TS_KEY_COLUMNS


# ---- the upsert ---------------------------------------------------------------


def test_edrRows_upsertThroughTheGenericPath_andAResendDoesNotDuplicate(session) -> None:
    """
    Given: an EDR batch pushed through runSyncUpsert
    When: the identical batch is sent again
    Then: the rows count once, the resend is reported as updates
    """
    tables = {
        "edr_imu_sample": {"rows": [_imuRow(1), _imuRow(2)]},
        "edr_light_sample": {"rows": [_lightRow(1)]},
    }

    first = server_sync.runSyncUpsert(session, _DEVICE, "b1", tables, syncHistoryId=7)
    session.commit()
    second = server_sync.runSyncUpsert(session, _DEVICE, "b2", tables, syncHistoryId=8)
    session.commit()

    assert first["edr_imu_sample"] == {"inserted": 2, "updated": 0, "errors": 0}
    assert first["edr_light_sample"] == {"inserted": 1, "updated": 0, "errors": 0}
    assert second["edr_imu_sample"] == {"inserted": 0, "updated": 2, "errors": 0}
    assert session.scalar(select(func.count()).select_from(EdrImuSample)) == 2
    assert session.scalar(select(func.count()).select_from(EdrLightSample)) == 1
    row = session.execute(select(EdrImuSample).where(EdrImuSample.source_id == 2)).scalar_one()
    assert row.source_device == _DEVICE
    assert row.seq == 2
    assert row.sync_batch_id == 8


class _CapturingSession:
    """Records the statement _upsertBatch would execute, for one dialect."""

    def __init__(self, dialectName: str) -> None:
        self.bind = SimpleNamespace(dialect=SimpleNamespace(name=dialectName))
        self.statements: list[Any] = []

    def execute(self, stmt: Any, rows: Any) -> None:
        self.statements.append(stmt)


def _legacyUpsertStmt(dialectName: str, model: type, allKeys: set[str]) -> Any:
    """``_upsertBatch``'s statement exactly as it was built BEFORE US-765.

    A verbatim copy of the pre-change body (conflict columns hard-coded), kept
    here so the comparison below is against the old behaviour, not against the
    new code restated.
    """
    table = model.__table__  # type: ignore[attr-defined]
    preserve = server_sync._PRESERVE_ON_UPDATE
    if dialectName in {"mysql", "mariadb"}:
        stmt = mysql_insert(table)
        updateCols = {
            c.name: stmt.inserted[c.name]
            for c in table.columns
            if c.name in allKeys and c.name not in preserve
        }
        return stmt.on_duplicate_key_update(**updateCols)
    stmt = sqlite_insert(table)
    updateCols = {
        c.name: getattr(stmt.excluded, c.name)
        for c in table.columns
        if c.name in allKeys and c.name not in preserve
    }
    return stmt.on_conflict_do_update(
        index_elements=["source_device", "source_id"],
        set_=updateCols,
    )


_PRE_EXISTING_TABLES = sorted(set(server_sync._TABLE_REGISTRY) - set(EDR_SYNC_TABLES))


@pytest.mark.parametrize("dialectName,dialect", [
    ("sqlite", sqlite.dialect()),
    ("mysql", mysql.dialect()),
    ("mariadb", mysql.dialect()),
])
@pytest.mark.parametrize("tableName", _PRE_EXISTING_TABLES)
def test_upsertSql_forEveryPreExistingTable_isByteIdenticalToBefore(
    tableName: str, dialectName: str, dialect: Any,
) -> None:
    """
    Given: a pre-existing synced table carrying every one of its columns
    When: _upsertBatch builds its statement
    Then: the compiled SQL is byte-identical to the pre-US-765 statement
    """
    model, _ = server_sync._TABLE_REGISTRY[tableName]
    allKeys = {c.name for c in model.__table__.columns}  # type: ignore[attr-defined]
    capture = _CapturingSession(dialectName)

    server_sync._upsertBatch(capture, model, [dict.fromkeys(allKeys)])  # type: ignore[arg-type]

    assert len(capture.statements) == 1
    actual = str(capture.statements[0].compile(dialect=dialect))
    expected = str(_legacyUpsertStmt(dialectName, model, allKeys).compile(dialect=dialect))
    assert actual == expected


def test_preExistingTableList_isNotEmpty() -> None:
    """An empty parametrize list would make the identity check above vacuous."""
    assert "realtime_data" in _PRE_EXISTING_TABLES
    assert len(_PRE_EXISTING_TABLES) == len(server_sync._TABLE_REGISTRY) - len(EDR_SYNC_TABLES)


@pytest.mark.parametrize("tableName", EDR_SYNC_TABLES)
def test_edrUpsert_conflictsOnTheModelKey_andNeverRewritesIt(tableName: str) -> None:
    model = _MODELS[tableName]
    allKeys = {c.name for c in model.__table__.columns}  # type: ignore[attr-defined]
    capture = _CapturingSession("sqlite")

    server_sync._upsertBatch(capture, model, [dict.fromkeys(allKeys)])  # type: ignore[arg-type]

    sql = str(capture.statements[0].compile(dialect=sqlite.dialect()))
    assert "ON CONFLICT (source_device, source_id, ts_utc) DO UPDATE SET" in sql
    setClause = sql.split("DO UPDATE SET", 1)[1]
    for keyCol in PRIMARY_KEY_COLUMNS:
        assert f"{keyCol} = " not in setClause


# ---- migration v0026 -------------------------------------------------------------


class _FakeServer:
    """A MariaDB stand-in: records SQL; a CREATE lands only if ``createLands``."""

    def __init__(self, *, createLands: bool = True) -> None:
        self.tables: set[str] = set()
        self.executed: list[str] = []
        self.probes: list[str] = []
        self.createLands = createLands

    def exists(self, addrs: Any, creds: Any, tableName: str, runner: Any) -> bool:
        self.probes.append(tableName)
        return tableName in self.tables

    def run(self, addrs: Any, creds: Any, sql: str, runner: Any) -> SimpleNamespace:
        self.executed.append(sql)
        if self.createLands:
            for tableName in EDR_SYNC_TABLES:
                if f"CREATE TABLE IF NOT EXISTS {tableName} (" in sql:
                    self.tables.add(tableName)
        return SimpleNamespace(returncode=0, stdout="", stderr="")


@pytest.fixture()
def server(monkeypatch: pytest.MonkeyPatch) -> _FakeServer:
    fake = _FakeServer()
    monkeypatch.setattr(mig, "serverTableExists", fake.exists)
    monkeypatch.setattr(mig, "_runServerSql", fake.run)
    return fake


def _ctx() -> SimpleNamespace:
    return SimpleNamespace(addrs=None, creds=None, runner=None)


def test_v0026_isRegisteredLast_andTheNumberIsUnique() -> None:
    versions = [m.version for m in ALL_MIGRATIONS]
    assert mig.VERSION == "0026"
    assert ALL_MIGRATIONS[-1] is mig.MIGRATION
    assert versions.count("0026") == 1
    assert versions == sorted(versions)


def test_v0026_onACleanSchema_createsBothTables_withTheGeneratorsDdl(server: _FakeServer) -> None:
    """
    Given: a schema with neither EDR table
    When: v0026 applies
    Then: it runs exactly the generator's DDL for each table and both exist
    """
    mig.apply(_ctx())  # type: ignore[arg-type]

    assert server.executed == [
        buildRawTableDdl(t, firstMonth=mig.FIRST_PARTITION_MONTH, months=mig.INITIAL_MONTHS)
        for t in EDR_SYNC_TABLES
    ]
    assert server.tables == set(EDR_SYNC_TABLES)


def test_v0026_appliedTwice_changesNothing_andTheProbePassesBothTimes(
    server: _FakeServer,
) -> None:
    mig.apply(_ctx())  # type: ignore[arg-type]
    schemaAfterFirst = set(server.tables)
    sqlAfterFirst = list(server.executed)
    server.probes.clear()

    mig.apply(_ctx())  # type: ignore[arg-type]

    assert server.tables == schemaAfterFirst
    assert server.executed == sqlAfterFirst
    # The post-condition probe runs on the no-op path too, for every table.
    assert server.probes[-len(EDR_SYNC_TABLES):] == list(EDR_SYNC_TABLES)


def test_v0026_raisesWhenACreateReportsSuccessButNoTableLanded(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    fake = _FakeServer(createLands=False)
    monkeypatch.setattr(mig, "serverTableExists", fake.exists)
    monkeypatch.setattr(mig, "_runServerSql", fake.run)

    with pytest.raises(MigrationError, match="absent after CREATE TABLE"):
        mig.apply(_ctx())  # type: ignore[arg-type]


def test_v0026_raisesWhenTheCreateFails(monkeypatch: pytest.MonkeyPatch) -> None:
    fake = _FakeServer()
    monkeypatch.setattr(mig, "serverTableExists", fake.exists)
    monkeypatch.setattr(
        mig, "_runServerSql",
        lambda addrs, creds, sql, runner: SimpleNamespace(
            returncode=1, stdout="", stderr="ERROR 1064",
        ),
    )

    with pytest.raises(MigrationError, match="ERROR 1064"):
        mig.apply(_ctx())  # type: ignore[arg-type]
