################################################################################
# File Name: v0026_us765_edr_raw_tables.py
# Purpose/Description: US-765 -- create the server EDR raw tables
#                      (edr_imu_sample, edr_light_sample) on obd2db. The DDL is
#                      GENERATED by src/common/edr/server_ddl.py from the shared
#                      contract (A-4); nothing here restates a column.
# Author: Rex (US-765)
# Creation Date: 2026-09-16
# Copyright: (c) 2026 Eclipse OBD-II Project. All rights reserved.
#
# Modification History:
# ================================================================================
# Date          | Author       | Description
# ================================================================================
# 2026-09-16    | Rex (US-765) | Initial -- US-734 plan Task 4 (number v0026 was
#               |              | free: highest in the tree was v0025).
# ================================================================================
################################################################################

"""Migration 0026: the EDR raw tables (US-765 / F-142, design US-734).

The Pi records IMU and light samples; until this migration the server had no
table to receive them.  Both tables are monthly ``RANGE COLUMNS(ts_utc)``
partitioned with a ``pmax`` catch-all, page-compressed, and keyed on the natural
``(source_device, source_id, ts_utc)`` -- the same key the ORM models declare as
their sync conflict columns.

The DDL comes from :func:`src.common.edr.server_ddl.buildRawTableDdl`.  A column
added to the contract appears here without editing this file, which is also why
this file must never be edited to change a column: a table that already exists
is untouched by ``CREATE TABLE IF NOT EXISTS`` (the A-10 trap).  A future column
needs its own migration with its own ``information_schema`` probe.

Forward-only and idempotent: an existence probe before each CREATE, and a
post-condition probe of EVERY table at the end of every run, including a run
that created nothing.  ``CREATE TABLE IF NOT EXISTS`` reports success when it
does nothing, so only the probe proves a table is there.
"""

from __future__ import annotations

from datetime import date

from scripts.apply_server_migrations import (
    MigrationError,
    _runServerSql,
    serverTableExists,
)
from src.common.edr.server_ddl import buildRawTableDdl
from src.common.edr.sync_contract import EDR_SYNC_TABLES
from src.server.migrations.runner import Migration, RunnerContext

__all__ = [
    'DESCRIPTION',
    'FIRST_PARTITION_MONTH',
    'INITIAL_MONTHS',
    'MIGRATION',
    'VERSION',
    'apply',
]


VERSION: str = '0026'
DESCRIPTION: str = (
    'US-765 -- edr_imu_sample + edr_light_sample: server raw EDR tables, '
    'monthly-partitioned on ts_utc, page-compressed, natural key '
    '(source_device, source_id, ts_utc); DDL generated from src/common/edr'
)

# The initial partition window, from the US-734 implementation plan (Task 4).
# The first partition is bounded only above, so Pi rows older than September
# 2026 land in p202609; later months beyond the window land in pmax until the
# nightly partition maintenance (US-734 spec section 7) splits it.
FIRST_PARTITION_MONTH: date = date(2026, 9, 1)
INITIAL_MONTHS: int = 4


def _createTable(ctx: RunnerContext, tableName: str) -> None:
    """Create one EDR raw table if it is absent."""
    if serverTableExists(ctx.addrs, ctx.creds, tableName, ctx.runner):
        return

    ddl = buildRawTableDdl(
        tableName, firstMonth=FIRST_PARTITION_MONTH, months=INITIAL_MONTHS,
    )
    res = _runServerSql(ctx.addrs, ctx.creds, ddl, ctx.runner)
    if res.returncode != 0:
        raise MigrationError(
            f'CREATE TABLE {tableName} failed: '
            f'{res.stderr.strip() or res.stdout.strip()}',
        )


def _assertTablesExist(ctx: RunnerContext) -> None:
    """Post-condition: every EDR raw table exists, or the migration fails."""
    for tableName in EDR_SYNC_TABLES:
        if not serverTableExists(ctx.addrs, ctx.creds, tableName, ctx.runner):
            raise MigrationError(
                f'{tableName} absent after CREATE TABLE reported success.  '
                f'CREATE TABLE IF NOT EXISTS succeeds when it does nothing, so '
                f'this almost always means the session landed in the wrong '
                f'database.  Investigate the MariaDB session context before '
                f're-running.',
            )


def apply(ctx: RunnerContext) -> None:
    """Create both EDR raw tables, then prove both exist."""
    for tableName in EDR_SYNC_TABLES:
        _createTable(ctx, tableName)
    _assertTablesExist(ctx)


MIGRATION: Migration = Migration(
    version=VERSION,
    description=DESCRIPTION,
    applyFn=apply,
)
