-- Table for static OBD2 data
CREATE TABLE OBD2StaticData (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vin TEXT UNIQUE,
    calibration_id TEXT,
    ecu_name TEXT,
    fuel_type TEXT,
    engine_displacement REAL,
    make TEXT,
    model TEXT,
    year TEXT,
    body_class TEXT,
    engine_cylinders TEXT,
    engine_hp TEXT,
    plant_country TEXT
);

CREATE TABLE OBD2StreamingData (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    static_data_id INTEGER,
    timestamp TEXT,
    rpm INTEGER,
    speed INTEGER,
    coolant_temp REAL,
    throttle_pos REAL,
    maf REAL,
    fuel_level REAL,
    intake_temp REAL,
    dtc_count INTEGER,
    engine_load REAL,
    fuel_trim_short_1 REAL,
    fuel_trim_long_1 REAL,
    fuel_trim_short_2 REAL,
    fuel_trim_long_2 REAL,
    o2_sensor_b1s1 REAL,
    o2_sensor_b1s2 REAL,
    intake_pressure REAL,
    timing_advance REAL,
    barometric_pressure REAL,
    absolute_throttle_pos REAL,
    battery_voltage REAL,
    warmups_since_dtc_clear INTEGER,
    distance_since_dtc_clear INTEGER,
    fuel_pressure REAL,
    evap_pressure REAL,
    catalyst_temp_b1s1 REAL,
    catalyst_temp_b1s2 REAL,
    oil_temp REAL,
    transmission_temp REAL,
    ambient_air_temp REAL,
    run_time INTEGER,
    distance_mil_on INTEGER,
    dtc_codes TEXT,
    FOREIGN KEY(static_data_id) REFERENCES OBD2StaticData(id)
);

